# Welcome to Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3],[4,5,6]], np.int8)

In [3]:
myarr[0,1]

2

In [4]:
myarr.shape

(2, 3)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 1, 45,  3],
       [ 4,  5,  6]], dtype=int8)

# Array Creation Conversion from other Python structures (e.g., lists, tuples)

In [8]:
listarray  = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.size

9

In [13]:
 setarray = np.array({25,35,25})

In [14]:
setarray

array({25, 35}, dtype=object)

# Intrinsic numpy  array creation objects (e.g., arange, ones, zeros, etc.)

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.shape

(2, 5)

In [18]:
zeros.dtype

dtype('float64')

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lsarray = np.linspace(1,25,5)

In [22]:
lsarray

array([ 1.,  7., 13., 19., 25.])

In [23]:
emp = np.empty((3,3))

In [24]:
emp

array([[1.60502324e-316, 2.46151512e-312, 2.41907520e-312],
       [2.05833592e-312, 9.76118064e-313, 2.22809558e-312],
       [2.14321575e-312, 0.00000000e+000, 0.00000000e+000]])

In [25]:
emp.dtype

dtype('float64')

In [26]:
emp_like = np.empty_like(lsarray)

In [27]:
emp_like

array([ 1.,  7., 13., 19., 25.])

In [28]:
ide = np.identity(3)

In [29]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
ide.size

9

In [31]:
ide.shape

(3, 3)

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr = arr.reshape(3,33)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr = arr.ravel()

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.shape

(99,)

In [41]:
 x = [[1,2,3],[4,5,6],[7,1,0]]

In [42]:
arr = np.array(x)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.sum(axis=0)

array([12,  8,  9])

In [45]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
arr.flat

In [49]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [50]:
arr.ndim

2

In [51]:
oneDarr = np.array([1,3,4,643,2])

In [52]:
oneDarr.argmax()

3

In [53]:
oneDarr = np.array([1,3,4,643,2])

In [54]:
oneDarr.argmin()

0

In [55]:
oneDarr = np.array([1,3,4,643,2])

In [56]:
oneDarr.argsort()

array([0, 4, 1, 2, 3])

In [57]:
twoDarr = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [58]:
twoDarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
twoDarr.argmax()

6

In [60]:
twoDarr = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [61]:
twoDarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
twoDarr.argmin()

8

In [63]:
twoDarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
twoDarr.argmax(axis = 0)

array([2, 1, 1])

In [65]:
twoDarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
twoDarr.argmax(axis=1)

array([2, 2, 0])

In [67]:
twoDarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
twoDarr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [69]:
twoDarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
twoDarr.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [71]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
array2= np.array([[3,2,1], [6,5,4], [9,8,7]])

In [73]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
array2

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [75]:
array1 + array2

array([[ 4,  4,  4],
       [10, 10, 10],
       [16, 16, 16]])

In [76]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
array1.min()

1

In [78]:
array1.max()

9

In [79]:
np.sqrt(array1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [80]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.where(array1 > 5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [82]:
myarr = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [83]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
np.count_nonzero(myarr)

8

In [85]:
np.nonzero(myarr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [86]:
type(np.nonzero(myarr))

tuple

In [87]:
import sys

In [88]:
Py_array = [0,4,55,2]

In [89]:
numPy_array = np.array(Py_array)

In [90]:
sys.getsizeof(1)* len(Py_array)

112

In [91]:
numPy_array.itemsize * numPy_array.size

32